version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: eelbar-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eelbar
    ports:
      - "5432:5432"
    volumes:
      - eelbar_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  eelbar_postgres_data:
    driver: local 